name: test
on:
  push:
    paths:
      - '**.ts'
      - 'package.json'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install
    - name: Run typcheck
      run: npm run typecheck
    - name: Run linter
      run: npm run test-lint
    - name: Run build
      run: npm run build